# Generated by Django 4.1.5 on 2023-03-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=30)),
                ('busnumber', models.IntegerField()),
                ('stopname', models.TextField()),
                ('attendence', models.BooleanField(default=1)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
