# Generated by Django 4.1.5 on 2023-03-16 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='password',
        ),
    ]
