# Generated by Django 4.1.5 on 2023-03-23 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_driver_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='studentname',
            new_name='rno',
        ),
    ]
