# Generated by Django 4.1.5 on 2023-01-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='bus_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
