# Generated by Django 4.1.5 on 2023-03-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addbus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbus',
            name='deviceId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addbus',
            name='ApiKey',
            field=models.CharField(max_length=1000),
        ),
    ]
