# Generated by Django 4.1.5 on 2023-03-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addbus', '0002_addbus_deviceid_alter_addbus_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbus',
            name='url',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addbus',
            name='ApiKey',
            field=models.TextField(),
        ),
    ]
